# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/notionink/adam/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#    vendor/notionink/adam/proprietary/proprietary/libsecril-client.so:obj/lib/libsecril-client.so

# All the blobs necessary for ADAM
PRODUCT_COPY_FILES := \
    vendor/notionink/adam/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/notionink/adam/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/notionink/adam/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/notionink/adam/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/notionink/adam/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/notionink/adam/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/notionink/adam/proprietary/lib/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/notionink/adam/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/notionink/adam/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/notionink/adam/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/notionink/adam/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/notionink/adam/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/notionink/adam/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
